export const PAIN_LOCATIONS = [
  "neck",
  "upper_back",
  "mid_back",
  "lower_back",
  "left_shoulder",
  "right_shoulder",
  "left_elbow",
  "right_elbow",
  "left_wrist",
  "right_wrist",
  "left_bicep",
  "right_bicep",
  "left_tricep",
  "right_tricep",
  "left_forearm",
  "right_forearm",
  "chest",
  "left_oblique",
  "right_oblique",
  "abdomen",
  "left_hip",
  "right_hip",
  "left_glute",
  "right_glute",
  "left_quad",
  "right_quad",
  "left_hamstring",
  "right_hamstring",
  "left_knee",
  "right_knee",
  "left_calf",
  "right_calf",
  "left_shin",
  "right_shin",
  "left_ankle",
  "right_ankle",
  "left_foot",
  "right_foot",
  "other",
] as const;

export type PainLocation = (typeof PAIN_LOCATIONS)[number];

export const VERSION_STATUSES = ["draft", "published", "archived"] as const;
export type VersionStatus = (typeof VERSION_STATUSES)[number];
