/**
 * Pulls a full snapshot of the DATABASE_URL database and writes it to
 * src/db/seed.backup.ts (git-ignored). Run this to capture prod data locally.
 *
 * Usage:
 *   DATABASE_URL=<prod-url> pnpm tsx src/db/extract.ts
 *   # or via package.json script:
 *   pnpm db:extract
 */

import { writeFileSync } from "fs";
import { join } from "path";
import { client, db } from "@/db";
import * as s from "@/db/schema";

// ---------------------------------------------------------------------------
// Serialisation helpers
// ---------------------------------------------------------------------------

function serializeValue(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (v instanceof Date) return `new Date(${JSON.stringify(v.toISOString())})`;
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  // jsonb / arrays (e.g. setsData, message content)
  return `(${JSON.stringify(v)} as any)`;
}

function serializeRows(rows: Record<string, unknown>[]): string {
  if (!rows.length) return "[]";
  const items = rows.map((row) => {
    const fields = Object.entries(row)
      .map(([k, v]) => `    ${k}: ${serializeValue(v)}`)
      .join(",\n");
    return `  {\n${fields},\n  }`;
  });
  return `[\n${items.join(",\n")}\n]`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function extract() {
  console.log("Reading from production…");

  const [
    allUsers,
    allUserRoles,
    allWorkoutPlans,
    allExercises,
    allWorkouts,
    allWorkoutExercises,
    allChats,
    allMessages,
  ] = await Promise.all([
    db.select().from(s.users),
    db.select().from(s.userRoles),
    db.select().from(s.workoutPlans),
    db.select().from(s.exercises),
    db.select().from(s.workouts),
    db.select().from(s.workoutExercises),
    db.select().from(s.chats),
    db.select().from(s.messages),
  ]);

  const counts = {
    users: allUsers.length,
    userRoles: allUserRoles.length,
    workoutPlans: allWorkoutPlans.length,
    exercises: allExercises.length,
    workouts: allWorkouts.length,
    workoutExercises: allWorkoutExercises.length,
    chats: allChats.length,
    messages: allMessages.length,
  };

  const countLine = Object.entries(counts)
    .filter(([, v]) => v > 0)
    .map(([k, v]) => `${v} ${k}`)
    .join(", ");

  // ---------------------------------------------------------------------------
  // Generate seed.backup.ts
  // ---------------------------------------------------------------------------

  const lines: string[] = [];

  lines.push(
    `// AUTO-GENERATED by src/db/extract.ts — do not edit manually`,
    `// Extracted: ${new Date().toISOString()}`,
    `// Videos and video join tables excluded.`,
    `import { sql } from "drizzle-orm";`,
    `import { client, db } from "@/db";`,
    `import {`,
    `  chats,`,
    `  exercises,`,
    `  messages,`,
    `  userRoles,`,
    `  users,`,
    `  workoutExercises,`,
    `  workoutPlans,`,
    `  workouts,`,
    `} from "@/db/schema";`,
    ``,
  );

  const tables: [string, Record<string, unknown>[]][] = [
    ["usersData", allUsers as Record<string, unknown>[]],
    ["userRolesData", allUserRoles as Record<string, unknown>[]],
    ["workoutPlansData", allWorkoutPlans as Record<string, unknown>[]],
    ["exercisesData", allExercises as Record<string, unknown>[]],
    ["workoutsData", allWorkouts as Record<string, unknown>[]],
    ["workoutExercisesData", allWorkoutExercises as Record<string, unknown>[]],
    ["chatsData", allChats as Record<string, unknown>[]],
    ["messagesData", allMessages as Record<string, unknown>[]],
  ];

  for (const [name, rows] of tables) {
    lines.push(`const ${name} = ${serializeRows(rows)};`, ``);
  }

  lines.push(
    `async function seed() {`,
    `  await db.transaction(async (tx) => {`,
    `    await tx.execute(sql` + "`" +
    `\n      TRUNCATE TABLE\n` +
    `        messages,\n` +
    `        workout_videos,\n` +
    `        workout_exercises,\n` +
    `        workouts,\n` +
    `        workout_plan_videos,\n` +
    `        exercise_videos,\n` +
    `        exercises,\n` +
    `        workout_plans,\n` +
    `        video_tags,\n` +
    `        videos,\n` +
    `        tags,\n` +
    `        chats,\n` +
    `        user_roles,\n` +
    `        users\n` +
    `      RESTART IDENTITY CASCADE\n` +
    `    ` + "`" + `);`,
    ``,
    `    // Insert in FK dependency order`,
    `    if (usersData.length) await tx.insert(users).values(usersData as any);`,
    `    if (userRolesData.length) await tx.insert(userRoles).values(userRolesData as any);`,
    `    if (workoutPlansData.length) await tx.insert(workoutPlans).values(workoutPlansData as any);`,
    `    if (exercisesData.length) await tx.insert(exercises).values(exercisesData as any);`,
    `    if (workoutsData.length) await tx.insert(workouts).values(workoutsData as any);`,
    `    if (workoutExercisesData.length) await tx.insert(workoutExercises).values(workoutExercisesData as any);`,
    `    if (chatsData.length) await tx.insert(chats).values(chatsData as any);`,
    `    if (messagesData.length) await tx.insert(messages).values(messagesData as any);`,
    `  });`,
    ``,
    `  console.log("Seeded: ${countLine}");`,
    `}`,
    ``,
    `seed()`,
    `  .catch((err) => {`,
    `    console.error(err);`,
    `    process.exitCode = 1;`,
    `  })`,
    `  .finally(() => client.end());`,
  );

  const outPath = join(process.cwd(), "src/db/seed.backup.ts");
  writeFileSync(outPath, lines.join("\n") + "\n");

  console.log(`Wrote ${outPath}`);
  for (const [k, v] of Object.entries(counts)) {
    console.log(`  ${k}: ${v}`);
  }
}

extract()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => client.end());
